# Generated by Django 5.2.14 on 2026-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='market',
            field=models.CharField(default='US', max_length=5),
        ),
    ]
