# Generated by Django 5.2.14 on 2026-05-11 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_portfolioposition_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('market', models.CharField(default='US', max_length=5)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioPosition',
        ),
    ]
